version: '3'
services:
  factory-mate:
    build:
      context: .
    entrypoint: tail -f /dev/null
    working_dir: /usr/src/factory-mate
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=factory-mate.localhost
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - .:/usr/src/factory-mate
      - ./docker/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - factory-mate
networks:
  factory-mate:
    external: false
